export const ALERTS_HUB_RULES = {
  USER_ONBOARD_INVITE_EMAIL: "TEAM_MEMBER_ONBOARD_INVITE",
  TEAM_MEMBER_RECEIVES_INVITE: "TEAM_MEMBER_RECEIVES_INVITE",
  TEAM_MEMBER_RECEIVES_FEEDBACK: "TEAM_MEMBER_RECEIVES_FEEDBACK",
  RESET_PASSWORD: "RESET_PASSWORD",
  FORGET_PASSWORD: "FORGET_PASSWORD",
  SIGN_UP_INVITATION: "SIGN_UP_INVITATION",
};
