import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();
export const Users = async () => {
  await prisma.users.createMany({
    data: [
      {
        id: 1,
        active: true,
        country_code: "+91",
        created_by: 1,
        updated_by: 1,
        date_of_birth: new Date(),
        date_of_joining: new Date(),
        designation: "Admin",
        email: "support@teckonnect.com",
        enabled_reason: null,
        firstname: "System",
        is_default: true,
        lastname: "Administrator",
        password:
          "$2a$10$Q11mTlgnpy/hVjGVlsj1fOVFd9vXwiDsv3VYL91uylA1kyGXWyb5S",
        pic_name: null,
        project_tour:
          '{"myDashboard":false,"rewardsAndRecognition":false,"hallOfFame":false,"ecards":false,"ecardInbox":false,"ecardTemplate":false,"badges":false,"createBadge":false,"myBadges":false,"awards":false,"createAward":false,"myAwards":false,"awardNominatorView":false,"awardNomination":false,"awardMyNominations":false,"awardApproval":false,"awardManage":false,"certificate":false,"myCertificate":false,"libraryBadges":false,"libraryAwards":false,"libraryCertificates":false,"socialWall":false,"ideaBox":false,"createIdeaBox":false,"myIdeas":false,"forum":false,"createforum":false,"myForums":false,"createPoll":false,"activePolls":false,"pollResults":false,"closedPolls":false,"createSurvey":false,"mySurveys":false,"surveyResults":false,"surveyQuestionBank":false,"rewardPoints":false,"portalSettings":false,"departmentMasters":false,"userManagement":false,"roleManagement":false,"hashTag":false}',
        sig_name: null,
        telephone_number: "0000000000",
        username: "Administrator",
        department_id: 1,
        manager_id: null,
        role_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 2,
        active: true,
        country_code: "+91",
        created_by: 1,
        updated_by: 1,
        date_of_birth: new Date(),
        date_of_joining: new Date(),
        designation: "developer",
        email: "email@gmail.com",
        enabled_reason: null,
        firstname: "System",
        is_default: false,
        lastname: "developer",
        password:
          "$2a$10$evvh/Ykfd1Dpiyy80Ft1yecO/kOHNjjLiZaQaPp6BN1qW7ZP875CG",
        pic_name: null,
        project_tour: "",
        sig_name: null,
        telephone_number: "8098782972",
        username: "User",
        department_id: 1,
        manager_id: null,
        role_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 3,
        active: true,
        country_code: "+91",
        created_by: 1,
        updated_by: 1,
        date_of_birth: new Date(),
        date_of_joining: new Date(),
        designation: "developer",
        email: "email2@gmail.com",
        enabled_reason: null,
        firstname: "System",
        is_default: false,
        lastname: "developer2",
        password:
          "$2a$10$dO8qSWnO8nFaIXQSzX1wg.rtoZh/48hZSB8xYKZlL.V8uDX0zIBJW",
        pic_name: null,
        project_tour: "",
        sig_name: null,
        telephone_number: "7864590874",
        username: "User2",
        department_id: 1,
        manager_id: null,
        role_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 4,
        active: true,
        country_code: "+91",
        created_by: 1,
        updated_by: 1,
        date_of_birth: new Date(),
        date_of_joining: new Date(),
        designation: "developer",
        email: "email3@gmail.com",
        enabled_reason: null,
        firstname: "System",
        is_default: false,
        lastname: "developer3",
        password:
          "$2a$10$/sBKH9cKWZNDkQImMvlDZea9tEI/GwiFxLo54LjB.0x/a/n.oGWhC",
        pic_name: null,
        project_tour: "",
        sig_name: null,
        telephone_number: "8769085467",
        username: "User3",
        department_id: 1,
        manager_id: null,
        role_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        id: 5,
        active: true,
        country_code: "+91",
        created_by: 1,
        updated_by: 1,
        date_of_birth: new Date(),
        date_of_joining: new Date(),
        designation: "developer",
        email: "email4@gmail.com",
        enabled_reason: null,
        firstname: "System",
        is_default: false,
        lastname: "developer4",
        password:
          "$2a$10$Y45EtbPMma5N3A2c7bflj.dqmzNPxJGG./LSU2lSNr4X9AuuSUADu",
        pic_name: null,
        project_tour: "",
        sig_name: null,
        telephone_number: "6758946908",
        username: "User4",
        department_id: 1,
        manager_id: null,
        role_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
      },
    ],
  });
};
